#!/bin/bash

SCRIPT_NAME="$(basename "$(readlink -f "$0")")"

HTTP_PORT=8081
ENABLE_THINKING="false"
USE_IMAGE=0
CONTEXT_SIZE=131072

LLAMA_SERVER="$HOME/Workspace/openai/llama.cpp/build/bin/llama-server"
GEMMA4_PATH="$HOME/Workspace/openai/llama.cpp/models/gemma-4-E4B-it-Q8_0.gguf"
MMPROJ_PATH="$HOME/Workspace/openai/llama.cpp/models/mmproj/mmproj-gemma-4-F16.gguf"


HELP_TEXT=$(cat <<-EOF
Usage: $SCRIPT_NAME [OPTIONS]

A helper script for running the Gemma 4 LLM using llama.cpp.

Options:
  --think           Enable thinking/reasoning mode
  --image           Enable image processing support
  --port, -p        Specify an HTTP port for llama-server. Default: $HTTP_PORT
  --help, -h        Display this help message and exit
EOF
)


while [ $# -gt 0 ]; do
  case "$1" in
    --think)
      ENABLE_THINKING="true"
      shift 1
      ;;
    --image)
      USE_IMAGE=1
      CONTEXT_SIZE=100000
      shift 1
      ;;
    -p|--port)
      HTTP_PORT="$2"
      shift 2
      ;;
    -h|--help)
      echo "$HELP_TEXT"
      exit 0
      ;;
    --)  # End argument parsing
      shift 1
      break
      ;;
    -*|--*=)  # Unsupported flags
      echo "Error: Unsupported flag $1" >&2
      echo
      echo "$HELP_TEXT"
      exit 1
      ;;
    *)  # Preserve positional arguments
      PARAMS="$PARAMS $(printf "%q" "$1")"
      shift 1
      ;;
  esac
done

# Set positional arguments in their proper place
eval set -- "$PARAMS"


GEMMA_CMD=(
  "$LLAMA_SERVER"
  --port "$HTTP_PORT"
  -m "$GEMMA4_PATH"
  --repeat_penalty 1.1
  --temp 1.0
  --top-k 64
  --top-p 0.95
  --min-p 0.0
  -c "$CONTEXT_SIZE"
  --chat-template-kwargs "{\"enable_thinking\":$ENABLE_THINKING}"
)

if [ "$USE_IMAGE" = "1" ]; then
  GEMMA_CMD+=("--mmproj" "$MMPROJ_PATH")
fi


# Start the Gemma4 server
"${GEMMA_CMD[@]}"
